apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: atlascore

type: Opaque

stringData:
  POSTGRES_USER: atlascore
  POSTGRES_PASSWORD: atlascore_password
  POSTGRES_DB: atlascore
  DATABASE_URL: postgresql+psycopg://atlascore:atlascore_password@postgres:5432/atlascore