from dataclasses import dataclass


@dataclass(frozen=True)
class CompanyEntity:
    name: str
    aliases: tuple[str, ...]
    domain: str | None = None


def favicon_url(domain: str | None) -> str | None:
    if domain is None:
        return None

    return f"https://www.google.com/s2/favicons?domain={domain}&sz=64"


COMPANY_ENTITIES: tuple[CompanyEntity, ...] = (
    CompanyEntity("OpenAI", ("OpenAI", "ChatGPT", "GPT-5", "GPT-5.5", "GPT-5.6", "GPT-Live", "Sora"), "openai.com"),
    CompanyEntity("Anthropic", ("Anthropic", "Claude", "Claude Code", "Fable"), "anthropic.com"),
    CompanyEntity("Google", ("Google", "Gemini", "Gemini API", "NotebookLM"), "google.com"),
    CompanyEntity("Google DeepMind", ("Google DeepMind", "DeepMind", "AlphaFold", "AlphaGo"), "deepmind.google"),
    CompanyEntity("Microsoft", ("Microsoft", "Microsoft 365 Copilot", "Copilot 365", "Microsoft Copilot", "Azure AI", "SymCrypt"), "microsoft.com"),
    CompanyEntity("Meta", ("Meta", "Llama", "Muse Spark", "Instagram"), "meta.com"),
    CompanyEntity("Apple", ("Apple", "Siri"), "apple.com"),
    CompanyEntity("Amazon", ("Amazon", "AWS", "Amazon Bedrock", "Bedrock", "SageMaker", "Quick Automate", "Quick"), "aws.amazon.com"),
    CompanyEntity("NVIDIA", ("NVIDIA", "Nemotron", "CUDA"), "nvidia.com"),
    CompanyEntity("Hugging Face", ("Hugging Face", "Transformers", "Hugging Face Hub"), "huggingface.co"),
    CompanyEntity("Mistral AI", ("Mistral AI", "Mistral", "Le Chat", "Robostral"), "mistral.ai"),
    CompanyEntity("GitHub", ("GitHub", "GitHub Copilot", "Copilot"), "github.com"),
    CompanyEntity("xAI", ("xAI", "Grok"), "x.ai"),
    CompanyEntity("DeepSeek", ("DeepSeek",), "deepseek.com"),
    CompanyEntity("Cursor", ("Cursor",), "cursor.com"),
    CompanyEntity("Perplexity", ("Perplexity",), "perplexity.ai"),
    CompanyEntity("Runway", ("Runway",), "runwayml.com"),
    CompanyEntity("Midjourney", ("Midjourney",), "midjourney.com"),
    CompanyEntity("Stability AI", ("Stability AI", "Stable Diffusion"), "stability.ai"),
    CompanyEntity("Cohere", ("Cohere", "Command R"), "cohere.com"),
    CompanyEntity("AI21 Labs", ("AI21", "AI21 Labs", "Jamba"), "ai21.com"),
    CompanyEntity("Databricks", ("Databricks", "MosaicML"), "databricks.com"),
    CompanyEntity("Snowflake", ("Snowflake",), "snowflake.com"),
    CompanyEntity("Oracle", ("Oracle",), "oracle.com"),
    CompanyEntity("Salesforce", ("Salesforce", "Einstein"), "salesforce.com"),
    CompanyEntity("Adobe", ("Adobe", "Firefly"), "adobe.com"),
    CompanyEntity("IBM", ("IBM", "watsonx"), "ibm.com"),
    CompanyEntity("Intel", ("Intel", "Gaudi"), "intel.com"),
    CompanyEntity("AMD", ("AMD", "ROCm"), "amd.com"),
    CompanyEntity("Cerebras", ("Cerebras",), "cerebras.ai"),
    CompanyEntity("Groq", ("Groq",), "groq.com"),
    CompanyEntity("SambaNova", ("SambaNova",), "sambanova.ai"),
    CompanyEntity("CoreWeave", ("CoreWeave",), "coreweave.com"),
    CompanyEntity("Together AI", ("Together AI", "Together"), "together.ai"),
    CompanyEntity("Fireworks AI", ("Fireworks AI", "Fireworks"), "fireworks.ai"),
    CompanyEntity("Anysphere", ("Anysphere",), "anysphere.co"),
    CompanyEntity("Replit", ("Replit",), "replit.com"),
    CompanyEntity("Codeium", ("Codeium", "Windsurf"), "windsurf.com"),
    CompanyEntity("Lovable", ("Lovable",), "lovable.dev"),
    CompanyEntity("Vercel", ("Vercel", "v0"), "vercel.com"),
    CompanyEntity("LangChain", ("LangChain", "LangGraph", "Deep Agents"), "langchain.com"),
    CompanyEntity("LlamaIndex", ("LlamaIndex",), "llamaindex.ai"),
    CompanyEntity("Pinecone", ("Pinecone",), "pinecone.io"),
    CompanyEntity("Weaviate", ("Weaviate",), "weaviate.io"),
    CompanyEntity("Qdrant", ("Qdrant",), "qdrant.tech"),
    CompanyEntity("Milvus", ("Milvus", "Zilliz"), "zilliz.com"),
    CompanyEntity("Stardog", ("Stardog",), "stardog.com"),
    CompanyEntity("Unsloth", ("Unsloth",), "unsloth.ai"),
    CompanyEntity("vLLM", ("vLLM",), "vllm.ai"),
    CompanyEntity("PyTorch", ("PyTorch",), "pytorch.org"),
    CompanyEntity("TensorFlow", ("TensorFlow",), "tensorflow.org"),
    CompanyEntity("Keras", ("Keras",), "keras.io"),
    CompanyEntity("JAX", ("JAX",), "jax.readthedocs.io"),
    CompanyEntity("Kaggle", ("Kaggle",), "kaggle.com"),
    CompanyEntity("Labelbox", ("Labelbox",), "labelbox.com"),
    CompanyEntity("Weights & Biases", ("Weights & Biases", "W&B", "wandb"), "wandb.ai"),
    CompanyEntity("Comet", ("Comet",), "comet.com"),
    CompanyEntity("H2O.ai", ("H2O.ai", "H2O"), "h2o.ai"),
    CompanyEntity("DataRobot", ("DataRobot",), "datarobot.com"),
    CompanyEntity("Palantir", ("Palantir",), "palantir.com"),
    CompanyEntity("Scale AI", ("Scale AI",), "scale.com"),
    CompanyEntity("Anduril", ("Anduril",), "anduril.com"),
    CompanyEntity("Figure AI", ("Figure AI", "Figure"), "figure.ai"),
    CompanyEntity("Boston Dynamics", ("Boston Dynamics",), "bostondynamics.com"),
    CompanyEntity("Tesla", ("Tesla", "Optimus"), "tesla.com"),
    CompanyEntity("Waymo", ("Waymo",), "waymo.com"),
    CompanyEntity("Waze", ("Waze",), "waze.com"),
    CompanyEntity("LinkedIn", ("LinkedIn",), "linkedin.com"),
    CompanyEntity("X", ("Twitter",), "x.com"),
    CompanyEntity("YouTube", ("YouTube",), "youtube.com"),
    CompanyEntity("TikTok", ("TikTok", "ByteDance"), "tiktok.com"),
    CompanyEntity("ByteDance", ("ByteDance", "Seedream"), "bytedance.com"),
    CompanyEntity("Alibaba", ("Alibaba", "Qwen"), "alibaba.com"),
    CompanyEntity("Baidu", ("Baidu", "ERNIE"), "baidu.com"),
    CompanyEntity("Tencent", ("Tencent", "Hunyuan"), "tencent.com"),
    CompanyEntity("Huawei", ("Huawei", "Ascend"), "huawei.com"),
    CompanyEntity("SK Hynix", ("SK Hynix",), "skhynix.com"),
    CompanyEntity("Samsung", ("Samsung",), "samsung.com"),
    CompanyEntity("Deutsche Telekom", ("Deutsche Telekom",), "telekom.com"),
    CompanyEntity("Bluesight", ("Bluesight",), "bluesight.com"),
    CompanyEntity("Henry Schein One", ("Henry Schein One",), "henryscheinone.com"),
    CompanyEntity("KTern.AI", ("KTern.AI", "KTern"), "ktern.com"),
    CompanyEntity("Jamf", ("Jamf",), "jamf.com"),
    CompanyEntity("Oak Lab", ("Oak Lab",), None),
    CompanyEntity("Soofi", ("Soofi", "Soofi S"), None),
    CompanyEntity("Aurora", ("Aurora 1.5",), "microsoft.com"),
    CompanyEntity("SymCrypt", ("SymCrypt",), "microsoft.com"),
    CompanyEntity("Flint", ("Flint",), "microsoft.com"),
    CompanyEntity("Minimax", ("MiniMax",), "minimax.io"),
    CompanyEntity("Zhipu AI", ("Zhipu", "GLM", "GLM-5.2"), "zhipuai.cn"),
)
